### ISSUE TITLE
many imagens

### ISSUE THREAD

**Issue by nagualcode** [Apisful/apisful-nuxtjs-ecommerce#2]
How could I have many images for one product?

**Comment by Eraser-str** [comment]
Hi @nagualcode.  You need to use a field with type `file` and `allow multiple` checkbox

![schema-field](https://user-images.githubusercontent.com/4465486/130100000-17a84cd0-98d6-485d-81d8-09fb315fbe61.png)

Then you can upload multiple images for one product

![product](https://user-images.githubusercontent.com/4465486/130100250-e91fa093-cb24-4d60-a9ff-6d39c29dfd0d.png)

And get the images as a list of links

![json](https://user-images.githubusercontent.com/4465486/130100357-7746b3e1-8aaf-49eb-951d-a1b6059be43e.png)

Also, check out our tutorial at https://www.apisful.com/tutorials/en/e-commerce-vue-js-nuxt-js-apisful .

**Comment by nagualcode** [comment]
Thank for the reply.
The site loads forever when trying to upload a 2mb .png . Is there a size limit?

**Comment by nagualcode** [comment]
if my schema has more than 10 entryes, the app web interface, shows only up to 10. Is there and endpoit to retrieve the full schema from curl?

**Comment by Eraser-str** [comment]
@nagualcode thank you for your reports and questions. We appreciate it. 

> The site loads forever when trying to upload a 2mb .png . Is there a size limit?

We experienced an issue with file uploading. It looks fixed now. Can you confirm everything is fine with files uploading? 
Keep in mind that files are limited to 20 megabytes. 

> if my schema has more than 10 entryes, the app web interface, shows only up to 10. Is there and endpoit to retrieve the full schema from curl?

There is no endpoint to retrieve the full schema from curl. Now you can see all your schema fields in the app web interface. Does it work for you?

**Comment by nagualcode** [comment]
> There is no endpoint to retrieve the full schema from curl. Now you can see all your schema fields in the app web interface. Does it work for you?

If I create a schema with 10+ entries, the web interface does not shows all of them.

Thank you.

**Comment by Eraser-str** [comment]
> > There is no endpoint to retrieve the full schema from curl. Now you can see all your schema fields in the app web interface. Does it work for you?
> 
> If I create a schema with 10+ entries, the web interface does not shows all of them.
> 
> Thank you.

I've just created more fields in my `Products` collection and can see all of them. Are we talking about the same page? 

![app apisful com_projects_0NxKVWv_collections_products_schema (1)](https://user-images.githubusercontent.com/4465486/130363784-9ad384f0-8449-4632-95ce-8d85b00029f4.png)

**Comment by nagualcode** [comment]
indeed, something may got broken on my browser... Thank you.
